import {Footer} from './components/footer'
import {Header} from './components/header'
import './globals.css'
import { Inter } from 'next/font/google'
import {aboutMyData,pages,contactMyLinks} from './date/date'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
    <head />
    <body>
      <Header name={aboutMyData.name} pages={pages} />
      <main className='sm:mb-32 mb-16 bg-gray'>{children}</main>
      <Footer contactMyLinks={contactMyLinks} />
    </body>
  </html>
  )
}
